function skillsMember() {
  return {
    name: 'Member',
    skills: [
      'JavaScript',
      'React',
      'Vue.js',
      'Node.js',
      'Express',
      'MongoDB',
      'PostgreSQL',
      'Docker',
      'Kubernetes',
      'CI/CD',
      'AWS',
      'Azure',
      'GCP',
      'Python',
      'Java',
      'C++',
      'C#',
      'HTML',
      'CSS',
      'SASS',
      'LESS',
      'Bootstrap',
      'Material-UI',
      'Tailwind CSS',
      'Jest',
      'Mocha',
      'Chai',
      'Cypress',
      'Puppeteer',
      'Git',
      'GitHub',
      'GitLab',
      'Bitbucket',
      'JIRA',
      'Trello',
      'Slack',
      'Discord',
    ],
  };
}